name: Django Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: feedback_project.settings
      DATABASE_URL: sqlite:///db.sqlite3
      TESTING: "true"
      GROQ_API_KEY: dummy_key

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django python-dotenv

      - name: Run tests
        run: python manage.py test